name: Sync to GitLab

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2 # checkout
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1 # mirroring
        with:
          target_repo_url: https://lab.ssafy.com/s10-blockchain-contract-sub2/S10P22D210.git
            
          # gitlab repo url ex) git@git.~~~~
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_KEY }} # github에 등록한 key name