name: sync to gitlab

on:
  push:
    branches:
      - dev
  pull_request:
    branches: 
      - dev

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "전수민"
          git config user.email "wjsaos2081@gmail.com"

      - name: Push to GitLab dev branch
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
        run: |
          git checkout dev
          git pull origin dev
          git checkout -b temp-dev
          git filter-branch --force --prune-empty --index-filter "git rm -rf --cached --ignore-unmatch .github" HEAD
          git remote add gitlab https://oauth2:$TARGET_TOKEN@lab.ssafy.com/s10-blockchain-contract-sub2/S10P22D210.git
          git push gitlab temp-dev:dev --force
          git checkout dev
          git branch -D temp-dev
